# Generated by Django 4.2.13 on 2025-08-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('text', 'Text Analysis'), ('audio', 'Voice Analysis'), ('facial', 'Facial Analysis'), ('multimodal', 'Multimodal Analysis')], max_length=20)),
                ('happiness', models.FloatField(default=0)),
                ('sadness', models.FloatField(default=0)),
                ('anger', models.FloatField(default=0)),
                ('fear', models.FloatField(default=0)),
                ('surprise', models.FloatField(default=0)),
                ('disgust', models.FloatField(default=0)),
                ('neutral', models.FloatField(default=0)),
                ('sentiment_score', models.FloatField(default=0)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('audio_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emotion analyses',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('emotion_analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='emotion_detection.emotionanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('exercise', 'Physical Exercise'), ('meditation', 'Meditation'), ('breathing', 'Breathing Techniques'), ('journaling', 'Journaling'), ('social', 'Social Connection'), ('professional', 'Professional Help'), ('resources', 'Mental Health Resources'), ('activities', 'Mood-Improving Activities'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('emotion_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='emotion_detection.emotionanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
