# Generated by Django 4.2.13 on 2025-08-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotion_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_title', models.CharField(blank=True, max_length=200, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('initial_mood', models.CharField(blank=True, max_length=50, null=True)),
                ('final_mood', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Assistant'), ('system', 'System Message')], max_length=10)),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('detected_emotions', models.JSONField(blank=True, default=dict)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='emotion_detection.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
