# Generated by Django 4.2.7 on 2025-08-10 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_guardian_email_user_guardian_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('counselor', 'Licensed Counselor'), ('psychologist', 'Clinical Psychologist'), ('therapist', 'Psychotherapist'), ('social_worker', 'Clinical Social Worker'), ('psychiatrist', 'Psychiatrist'), ('life_coach', 'Life Coach'), ('crisis_specialist', 'Crisis Intervention Specialist')], max_length=50)),
                ('languages', models.JSONField(default=list)),
                ('years_experience', models.IntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('certifications', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'In Session'), ('offline', 'Offline'), ('break', 'On Break')], default='available', max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('bio', models.TextField()),
                ('areas_of_expertise', models.JSONField(default=list)),
                ('approach', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('session_duration', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-average_rating', '-status'],
            },
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='anxiety_level',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='depression_level',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='sleep_quality',
        ),
        migrations.RemoveField(
            model_name='mentalhealthassessment',
            name='stress_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consent_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_consented_to_data_collection',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_consented_to_terms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sleep_quality',
        ),
        migrations.AddField(
            model_name='mentalhealthassessment',
            name='anxiety_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='mentalhealthassessment',
            name='depression_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='mentalhealthassessment',
            name='overall_mood',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='mentalhealthassessment',
            name='stress_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='anxiety_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='depression_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stress_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Supporter'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('crisis_related', models.BooleanField(default=False)),
                ('room_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_feedback', models.TextField(blank=True)),
                ('supporter_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='users.mentalhealthsupporter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mentalhealthsupporter',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_supporter', to='users.videosession'),
        ),
    ]
